algoritmo "6"
var
a,b,troca: real
              inicio
              escreva("Escreva o valor da variavel A: ")
              leia (A)
              escreva("Escreva o valor da variavel B: ")
              leia (B)
              troca <- a
              a <- b
              b <- troca
              limpatela
              escreval("o valor de A é:", a)
              escreval ("o valor de B é:", b)
              fimalgoritmo